// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin.proto

package pluginproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_Initialize_FullMethodName    = "/plugin.ProviderService/Initialize"
	ProviderService_Shutdown_FullMethodName      = "/plugin.ProviderService/Shutdown"
	ProviderService_StorageSave_FullMethodName   = "/plugin.ProviderService/StorageSave"
	ProviderService_StorageGet_FullMethodName    = "/plugin.ProviderService/StorageGet"
	ProviderService_StorageDelete_FullMethodName = "/plugin.ProviderService/StorageDelete"
	ProviderService_StorageURL_FullMethodName    = "/plugin.ProviderService/StorageURL"
	ProviderService_StorageExists_FullMethodName = "/plugin.ProviderService/StorageExists"
	ProviderService_Search_FullMethodName        = "/plugin.ProviderService/Search"
	ProviderService_SearchSuggest_FullMethodName = "/plugin.ProviderService/SearchSuggest"
	ProviderService_SearchIndex_FullMethodName   = "/plugin.ProviderService/SearchIndex"
	ProviderService_SearchRemove_FullMethodName  = "/plugin.ProviderService/SearchRemove"
	ProviderService_SearchRebuild_FullMethodName = "/plugin.ProviderService/SearchRebuild"
	ProviderService_Notify_FullMethodName        = "/plugin.ProviderService/Notify"
	ProviderService_CaptchaVerify_FullMethodName = "/plugin.ProviderService/CaptchaVerify"
	ProviderService_HandleHTTP_FullMethodName    = "/plugin.ProviderService/HandleHTTP"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderService is the main plugin service interface.
// Each plugin process serves this via go-plugin.
type ProviderServiceClient interface {
	// Lifecycle
	Initialize(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// StorageProvider methods
	StorageSave(ctx context.Context, in *StorageSaveRequest, opts ...grpc.CallOption) (*StorageSaveResponse, error)
	StorageGet(ctx context.Context, in *StorageGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StorageChunk], error)
	StorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error)
	StorageURL(ctx context.Context, in *StorageURLRequest, opts ...grpc.CallOption) (*StorageURLResponse, error)
	StorageExists(ctx context.Context, in *StorageExistsRequest, opts ...grpc.CallOption) (*StorageExistsResponse, error)
	// SearchProvider methods
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchSuggest(ctx context.Context, in *SearchSuggestRequest, opts ...grpc.CallOption) (*SearchSuggestResponse, error)
	SearchIndex(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error)
	SearchRemove(ctx context.Context, in *SearchRemoveRequest, opts ...grpc.CallOption) (*SearchRemoveResponse, error)
	SearchRebuild(ctx context.Context, in *SearchRebuildRequest, opts ...grpc.CallOption) (*SearchRebuildResponse, error)
	// NotifierProvider methods
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// CaptchaProvider methods
	CaptchaVerify(ctx context.Context, in *CaptchaVerifyRequest, opts ...grpc.CallOption) (*CaptchaVerifyResponse, error)
	// Custom HTTP route handling
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Initialize(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ProviderService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ProviderService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StorageSave(ctx context.Context, in *StorageSaveRequest, opts ...grpc.CallOption) (*StorageSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSaveResponse)
	err := c.cc.Invoke(ctx, ProviderService_StorageSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StorageGet(ctx context.Context, in *StorageGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StorageChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[0], ProviderService_StorageGet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StorageGetRequest, StorageChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_StorageGetClient = grpc.ServerStreamingClient[StorageChunk]

func (c *providerServiceClient) StorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDeleteResponse)
	err := c.cc.Invoke(ctx, ProviderService_StorageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StorageURL(ctx context.Context, in *StorageURLRequest, opts ...grpc.CallOption) (*StorageURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageURLResponse)
	err := c.cc.Invoke(ctx, ProviderService_StorageURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StorageExists(ctx context.Context, in *StorageExistsRequest, opts ...grpc.CallOption) (*StorageExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageExistsResponse)
	err := c.cc.Invoke(ctx, ProviderService_StorageExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ProviderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SearchSuggest(ctx context.Context, in *SearchSuggestRequest, opts ...grpc.CallOption) (*SearchSuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSuggestResponse)
	err := c.cc.Invoke(ctx, ProviderService_SearchSuggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SearchIndex(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchIndexResponse)
	err := c.cc.Invoke(ctx, ProviderService_SearchIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SearchRemove(ctx context.Context, in *SearchRemoveRequest, opts ...grpc.CallOption) (*SearchRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRemoveResponse)
	err := c.cc.Invoke(ctx, ProviderService_SearchRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SearchRebuild(ctx context.Context, in *SearchRebuildRequest, opts ...grpc.CallOption) (*SearchRebuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRebuildResponse)
	err := c.cc.Invoke(ctx, ProviderService_SearchRebuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, ProviderService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CaptchaVerify(ctx context.Context, in *CaptchaVerifyRequest, opts ...grpc.CallOption) (*CaptchaVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaVerifyResponse)
	err := c.cc.Invoke(ctx, ProviderService_CaptchaVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, ProviderService_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ProviderService is the main plugin service interface.
// Each plugin process serves this via go-plugin.
type ProviderServiceServer interface {
	// Lifecycle
	Initialize(context.Context, *InitRequest) (*InitResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// StorageProvider methods
	StorageSave(context.Context, *StorageSaveRequest) (*StorageSaveResponse, error)
	StorageGet(*StorageGetRequest, grpc.ServerStreamingServer[StorageChunk]) error
	StorageDelete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error)
	StorageURL(context.Context, *StorageURLRequest) (*StorageURLResponse, error)
	StorageExists(context.Context, *StorageExistsRequest) (*StorageExistsResponse, error)
	// SearchProvider methods
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchSuggest(context.Context, *SearchSuggestRequest) (*SearchSuggestResponse, error)
	SearchIndex(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error)
	SearchRemove(context.Context, *SearchRemoveRequest) (*SearchRemoveResponse, error)
	SearchRebuild(context.Context, *SearchRebuildRequest) (*SearchRebuildResponse, error)
	// NotifierProvider methods
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// CaptchaProvider methods
	CaptchaVerify(context.Context, *CaptchaVerifyRequest) (*CaptchaVerifyResponse, error)
	// Custom HTTP route handling
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) Initialize(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedProviderServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedProviderServiceServer) StorageSave(context.Context, *StorageSaveRequest) (*StorageSaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorageSave not implemented")
}
func (UnimplementedProviderServiceServer) StorageGet(*StorageGetRequest, grpc.ServerStreamingServer[StorageChunk]) error {
	return status.Error(codes.Unimplemented, "method StorageGet not implemented")
}
func (UnimplementedProviderServiceServer) StorageDelete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorageDelete not implemented")
}
func (UnimplementedProviderServiceServer) StorageURL(context.Context, *StorageURLRequest) (*StorageURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorageURL not implemented")
}
func (UnimplementedProviderServiceServer) StorageExists(context.Context, *StorageExistsRequest) (*StorageExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorageExists not implemented")
}
func (UnimplementedProviderServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedProviderServiceServer) SearchSuggest(context.Context, *SearchSuggestRequest) (*SearchSuggestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSuggest not implemented")
}
func (UnimplementedProviderServiceServer) SearchIndex(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchIndex not implemented")
}
func (UnimplementedProviderServiceServer) SearchRemove(context.Context, *SearchRemoveRequest) (*SearchRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRemove not implemented")
}
func (UnimplementedProviderServiceServer) SearchRebuild(context.Context, *SearchRebuildRequest) (*SearchRebuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRebuild not implemented")
}
func (UnimplementedProviderServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedProviderServiceServer) CaptchaVerify(context.Context, *CaptchaVerifyRequest) (*CaptchaVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptchaVerify not implemented")
}
func (UnimplementedProviderServiceServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Initialize(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StorageSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StorageSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StorageSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StorageSave(ctx, req.(*StorageSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StorageGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StorageGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).StorageGet(m, &grpc.GenericServerStream[StorageGetRequest, StorageChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_StorageGetServer = grpc.ServerStreamingServer[StorageChunk]

func _ProviderService_StorageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StorageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StorageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StorageDelete(ctx, req.(*StorageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StorageURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StorageURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StorageURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StorageURL(ctx, req.(*StorageURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StorageExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StorageExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StorageExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StorageExists(ctx, req.(*StorageExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SearchSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SearchSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SearchSuggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SearchSuggest(ctx, req.(*SearchSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SearchIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SearchIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SearchIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SearchIndex(ctx, req.(*SearchIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SearchRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SearchRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SearchRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SearchRemove(ctx, req.(*SearchRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SearchRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SearchRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SearchRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SearchRebuild(ctx, req.(*SearchRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CaptchaVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CaptchaVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CaptchaVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CaptchaVerify(ctx, req.(*CaptchaVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ProviderService_Initialize_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ProviderService_Shutdown_Handler,
		},
		{
			MethodName: "StorageSave",
			Handler:    _ProviderService_StorageSave_Handler,
		},
		{
			MethodName: "StorageDelete",
			Handler:    _ProviderService_StorageDelete_Handler,
		},
		{
			MethodName: "StorageURL",
			Handler:    _ProviderService_StorageURL_Handler,
		},
		{
			MethodName: "StorageExists",
			Handler:    _ProviderService_StorageExists_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _ProviderService_Search_Handler,
		},
		{
			MethodName: "SearchSuggest",
			Handler:    _ProviderService_SearchSuggest_Handler,
		},
		{
			MethodName: "SearchIndex",
			Handler:    _ProviderService_SearchIndex_Handler,
		},
		{
			MethodName: "SearchRemove",
			Handler:    _ProviderService_SearchRemove_Handler,
		},
		{
			MethodName: "SearchRebuild",
			Handler:    _ProviderService_SearchRebuild_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _ProviderService_Notify_Handler,
		},
		{
			MethodName: "CaptchaVerify",
			Handler:    _ProviderService_CaptchaVerify_Handler,
		},
		{
			MethodName: "HandleHTTP",
			Handler:    _ProviderService_HandleHTTP_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StorageGet",
			Handler:       _ProviderService_StorageGet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
